### ISSUE TITLE
Nullpointer Exception in JCypher when connecting with Neo4j 3.0.1

### ISSUE THREAD

**Issue by wouterd** [Wolfgang-Schuetzelhofer/jcypher#22]
Neo4J version: 3.0.1
JCypher version: 3.4.0

When trying to get errors from a queryresult, the JCypher library throws an NPE. I'm trying to investigate, but maybe you have an idea already? :)

```
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  java.lang.NullPointerException 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at iot.jcypher.query.JcQueryResult.getDBErrors(JcQueryResult.java:161) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at com.partup.UpdateNeo4jActor.com$partup$UpdateNeo4jActor$$sendToNeo4j(UpdateNeo4jActor.scala:121) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at com.partup.UpdateNeo4jActor$$anonfun$receive$1.applyOrElse(UpdateNeo4jActor.scala:74) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at com.partup.UpdateNeo4jActor.aroundReceive(UpdateNeo4jActor.scala:43) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at akka.actor.ActorCell.invoke(ActorCell.scala:487) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at akka.dispatch.Mailbox.run(Mailbox.scala:221) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) 
May 30 23:23:36 prod-api-2 prod-api-2.8e94bbf8:  	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) 
```

**Comment by Wolfgang-Schuetzelhofer** [comment]
Sorry, but JCypher is currently not ready for Neo4J 3.x
The August release (3.5.0) is planned to support Neo4J 3.x.

best regards,
Wolfgang

**Comment by wouterd** [comment]
Thanks for the info, we'll downgrade. :)

**Comment by Wolfgang-Schuetzelhofer** [comment]
JCypher has been tested against Neo4J 2.3.2 :)
