### ISSUE TITLE
IDomainAccess loadById() not work with GraphAware Neo4j UUID

### ISSUE THREAD

**Issue by ZengII** [Wolfgang-Schuetzelhofer/jcypher#52]
Hi Wolfgang,
I am trying neo4j and GraphAware Neo4j UUID.
I use Neo4j Desktop to active a  local neo4j DB.

The jar files in the plugin directory are as below:
**graphaware-server-community-all-3.5.2.53.jar
graphaware-uuid-3.5.2.53.17.jar**

The jar version in my project is as below
**<jcypher.version>4.2.0</jcypher.version>
<neo4j.version>3.5.2</neo4j.version>**

When I execute the code loadById()
`return domainAccess.loadById(Author.class, 0, authorId);`

I get the exception :

**iot.jcypher.query.result.JcResultException
	at iot.jcypher.domain.internal.DomainAccess$DomainAccessHandler.queryConcreteTypes(DomainAccess.java:978)
	at iot.jcypher.domain.internal.DomainAccess$DomainAccessHandler.loadByIds(DomainAccess.java:583)
	at iot.jcypher.domain.internal.DomainAccess.loadByIds(DomainAccess.java:185)
	at iot.jcypher.domain.internal.DomainAccess.loadById(DomainAccess.java:176)
	at org.cj.demo.dao.AuthorDao.queryAuthorWithUuidById(AuthorDao.java:65)**

If I use native cypher, everything is ok.
```
String queryUuidById(long authorId) {
    JcNode n = new JcNode("n");
    JcQuery query = new JcQuery();

    query.setClauses(
        new IClause[] {NATIVE.cypher(String.format("MATCH (n:Author) WHERE id(n)=%d RETURN n.uuid", authorId)),});

    JcQueryResult result = dbAccess.execute(query);
    List<String> rtn = result.resultOf(new JcString("n.uuid"));

    return rtn.get(0);
}
```

cheers,
Zeng

**Comment by Wolfgang-Schuetzelhofer** [comment]
Hi Zeng,
sorry for the late reply, I was out of office for one week.
Loading objects via DomainAccess is only possible if the objects have previously been stored via DomainAccess.
Using DomainAccess you work with real domain objects, and to do so, JCypher stores additional meta data with the graph. This meta data is then used to restore domain objects when loading them.
I hope that helps.

cheers,
Wolfgang

**Comment by ZengII** [comment]
Thanks Wolfgang,
The final solution I find to synchronize DomainState and  meta data in Neo4j DB is to store the object twice.
At the second time,  store the object with the queried uuid.

**Comment by ZengII** [comment]
I wonder if we can use a dirty method to mark the object in the DomainState is dirty.
And at the next time, when we use loadbyId() or other query, 
the dirty object in the DomainState can be refresh directly with the meta data in Neo4j DB

Maybe with the dirty method, we can handle more complicated cases.

cheers,
Zeng

**Comment by Wolfgang-Schuetzelhofer** [comment]
Hi Zeng,
I will have a look at this for the next release. But basically the problem is a concurrent update of a node's property in the db by another source (not by means of JCypher), hence synchronicity is broken.

cheers,
Wolfgang

**Comment by ZengII** [comment]
Thanks, Wolfgang,
Refer to the Github of GraphAware Neo4j UUID
https://github.com/graphaware/neo4j-uuid#using-graphaware-uuid
, the tutorial says
If you create a node and return it immediately, its contents will not reflect changes performed by transaction event handlers, thus the UUID will not be available. 

A separate call must be made to get the UUID, for example:
```
CREATE (n:User {name: "Alice"}) RETURN id(n)
// Later, using saved ID from above:
MATCH (n) WHERE id(n) = 123 RETURN n.uuid
```
Maybe in the case, the update order can be expected more than a concurrent update.
